# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from assetproto import student_pb2 as student__pb2


class StudentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateStudent = channel.unary_unary(
                '/students.StudentService/CreateStudent',
                request_serializer=student__pb2.CreateStudentRequest.SerializeToString,
                response_deserializer=student__pb2.CreateStudentRequest.FromString,
                )
        self.GetStudent = channel.unary_unary(
                '/students.StudentService/GetStudent',
                request_serializer=student__pb2.GetStudentRequest.SerializeToString,
                response_deserializer=student__pb2.CreateStudentRequest.FromString,
                )
        self.GetRedisData = channel.unary_unary(
                '/students.StudentService/GetRedisData',
                request_serializer=student__pb2.GetRedisRequest.SerializeToString,
                response_deserializer=student__pb2.GetRedisResponse.FromString,
                )


class StudentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateStudent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStudent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRedisData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StudentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateStudent': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateStudent,
                    request_deserializer=student__pb2.CreateStudentRequest.FromString,
                    response_serializer=student__pb2.CreateStudentRequest.SerializeToString,
            ),
            'GetStudent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStudent,
                    request_deserializer=student__pb2.GetStudentRequest.FromString,
                    response_serializer=student__pb2.CreateStudentRequest.SerializeToString,
            ),
            'GetRedisData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRedisData,
                    request_deserializer=student__pb2.GetRedisRequest.FromString,
                    response_serializer=student__pb2.GetRedisResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'students.StudentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StudentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateStudent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/students.StudentService/CreateStudent',
            student__pb2.CreateStudentRequest.SerializeToString,
            student__pb2.CreateStudentRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStudent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/students.StudentService/GetStudent',
            student__pb2.GetStudentRequest.SerializeToString,
            student__pb2.CreateStudentRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRedisData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/students.StudentService/GetRedisData',
            student__pb2.GetRedisRequest.SerializeToString,
            student__pb2.GetRedisResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
