# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: student.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstudent.proto\x12\x08students\"\\\n\x14\x43reateStudentRequest\x12\x0e\n\x06rollno\x18\x01 \x01(\x05\x12\x10\n\x08\x66ullname\x18\x02 \x01(\t\x12\x10\n\x08standard\x18\x03 \x01(\x05\x12\x10\n\x08\x64ivision\x18\x04 \x01(\t\"#\n\x11GetStudentRequest\x12\x0e\n\x06rollno\x18\x01 \x01(\x05\"\x1e\n\x0fGetRedisRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\" \n\x10GetRedisResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2\xf9\x01\n\x0eStudentService\x12Q\n\rCreateStudent\x12\x1e.students.CreateStudentRequest\x1a\x1e.students.CreateStudentRequest\"\x00\x12K\n\nGetStudent\x12\x1b.students.GetStudentRequest\x1a\x1e.students.CreateStudentRequest\"\x00\x12G\n\x0cGetRedisData\x12\x19.students.GetRedisRequest\x1a\x1a.students.GetRedisResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'student_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CREATESTUDENTREQUEST']._serialized_start=27
  _globals['_CREATESTUDENTREQUEST']._serialized_end=119
  _globals['_GETSTUDENTREQUEST']._serialized_start=121
  _globals['_GETSTUDENTREQUEST']._serialized_end=156
  _globals['_GETREDISREQUEST']._serialized_start=158
  _globals['_GETREDISREQUEST']._serialized_end=188
  _globals['_GETREDISRESPONSE']._serialized_start=190
  _globals['_GETREDISRESPONSE']._serialized_end=222
  _globals['_STUDENTSERVICE']._serialized_start=225
  _globals['_STUDENTSERVICE']._serialized_end=474
# @@protoc_insertion_point(module_scope)
